deploy:
  provider: releases
  api_key: $apikey
  cleanup: false
  file_glob: true
  file:
  - "/home/travis/build/NeumimTo/NT-RPG/Plugin/target/NT-RPG-*.jar"
  - "/home/travis/build/NeumimTo/NT-RPG/Skills/target/NT-*.jar"
branches:
  only:
    - /^v.*$/
language: java
jdk:
  - openjdk8
